### ISSUE TITLE
Allow for customisation of the workflow at course level

### ISSUE THREAD

**Issue by mkpelletier** [moodleou/moodle-block_workflow#3]
I would like to be able to customise the workflow after it has been attached to the course.  While most courses will share the majority of the workflow steps, I imagine it would be common to have extra steps specific to a given course.  For this to be truly useful, the customisation of the workflow would have to persist between course resets/backups, otherwise you would need to recreate those steps every time the course is reset.  However, I imagine this last bit might be more tricky to implement.

Thoughts?

**Comment by timhunt** [comment]
That would be incredibly difficult to implement, to the point of being essentially infeasible.

The way it works is: workflows have to be defined centrally (but you can have as many different workflows as you want). Each course can then choose which workflow to use. We are not going to change that fundamental scheme. Sorry.
