### ISSUE TITLE
Workflow v1.9 Error email 

### ISSUE THREAD

**Issue by kingsalahadeen** [moodleou/moodle-block_workflow#6]
Hello , i need you help please 
I have Workflow v1.9 for Moodle 3.5+
and i create an email template (mmm)  in workflow area , 
and when i call script i use
email {mmm} to {role1} {role2} 
but i'm getting error 
The script you specified was invalid. An invalid email email was specified. The email specified was '{mmm}'
Thanks in Advance

**Comment by kingsalahadeen** [comment]
Okay , i got the solution , the role is short-name role not full name , document has a mistake !

**Comment by timhunt** [comment]
Well done for working it out.

Which docs were you looking at? Would be good to fix.

**Comment by kingsalahadeen** [comment]
https://docs.moodle.org/38/en/The_OU_workflow_system

**Comment by kingsalahadeen** [comment]
also i'm wondering , why calling script is having '{' 
email {templatename} to {role1} {role2}
while the correct script should be 
email templatename  to role1 role2

**Comment by timhunt** [comment]
Well, I think that was an attempt to clearly indicate which parts of the command you needed to replace with actual values, but clearly not clear.

Hope these amends help: https://docs.moodle.org/38/en/index.php?title=The_OU_workflow_system&type=revision&diff=136812&oldid=105540. Thank you for reporting the issue.

Note, Moodle docs is a wiki. Please feel free to edit this page yourself, if you think of improvements.

**Comment by kingsalahadeen** [comment]
Hi , 
i want help in workflow plugin , i do not want use it as a block_workflow , i want it in Activities , because there is an issue when i want add more than one workflow in the block menu . i can not add more than one . so i feel it's more nice if it's in activity . can you help me please ?

**Comment by kingsalahadeen** [comment]
or how i can enable multi instance for the block ?
